
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package it.unimi.di.fachini.imp.parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int UNARY = 9;
  public static final int MOD = 8;
  public static final int READ = 30;
  public static final int OPEN_PAREN = 17;
  public static final int LT = 12;
  public static final int NE = 11;
  public static final int IDENT = 32;
  public static final int ELSE = 23;
  public static final int PLUS = 4;
  public static final int WHILE = 24;
  public static final int WRITELN = 29;
  public static final int SEMI_COLON = 3;
  public static final int IF = 22;
  public static final int ClOSE_CURLY_BRACE = 20;
  public static final int GT = 13;
  public static final int WRITE = 27;
  public static final int LE = 14;
  public static final int NUM = 31;
  public static final int DO = 25;
  public static final int STRING = 33;
  public static final int OPEN_CURLY_BRACE = 19;
  public static final int COMMA = 2;
  public static final int EOF = 0;
  public static final int DIV = 7;
  public static final int CLOSE_PAREN = 18;
  public static final int GE = 15;
  public static final int MINUS = 5;
  public static final int error = 1;
  public static final int EQ = 10;
  public static final int ASSIGNTO = 16;
  public static final int FOR = 26;
  public static final int WRITEMSG = 28;
  public static final int MUL = 6;
  public static final int VAR = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMMA",
  "SEMI_COLON",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "UNARY",
  "EQ",
  "NE",
  "LT",
  "GT",
  "LE",
  "GE",
  "ASSIGNTO",
  "OPEN_PAREN",
  "CLOSE_PAREN",
  "OPEN_CURLY_BRACE",
  "ClOSE_CURLY_BRACE",
  "VAR",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "WRITE",
  "WRITEMSG",
  "WRITELN",
  "READ",
  "NUM",
  "IDENT",
  "STRING"
  };
}

